#!/bin/bash
#gnome-terminal doemon without systemd
export LANG=en_US.UTF-8
killall gnome-terminal-daemon || true
i=1
while [ $i -lt 10 ] ;
do
    /usr/libexec/gnome-terminal-server || sleep $i
    i=$(($i+1))
done
exit 1
