#!/bin/bash -ex
# Highly opinionated wrapper for Arch Linux packaging
# Modified my SulinOS team

exec meson setup \
  --prefix        /usr \
  --libexecdir    /usr/libexec \
  --sbindir       /sbin \
  --sysconfdir=   /etc   \
  --localstatedir=/var  \
  --buildtype     plain \
  --auto-features enabled \
  --wrap-mode     nodownload \
  -D              b_lto=true \
  -D              b_pie=true \
  "$@"
